#!/usr/bin/env python3
"""Generate capm-glass.html (Liquid Glass build) from capm-pro.html.

Never edit capm-glass.html by hand — edit capm-pro.html, then rerun:
  python3 make_glass.py

The glass build is a pure reskin + motion layer on top of the pro build
(content, engine, and state keys identical, so progress carries over):
  1. Liquid-glass surfaces: every card/panel becomes translucent frosted
     glass (backdrop-filter blur+saturate, specular top edge, soft depth).
  2. A fixed color-field behind the app: three huge blurred gradient blobs
     drifting on long offset cycles, visible through every panel.
  3. Floating glass dock: the mobile tab bar detaches into a rounded
     pill hovering above the bottom edge.
  4. 3D view transitions: the existing directional slide classes get
     perspective rotateY/rotateX + translateZ keyframes, and #screen
     gains a perspective so views swing in like glass panes.

Every replacement asserts its match count (repo editing rule) so pro-build
changes that move an anchor fail loudly here.
"""

SRC = "capm-pro.html"
OUT = "capm-glass.html"

GLASS_CSS = """  /* ===== LIQUID GLASS SKIN (generated by make_glass.py) ===== */
  body{background:#090c10;}
  .glassbg{position:fixed;inset:-12%;z-index:0;pointer-events:none;filter:blur(72px) saturate(1.35);}
  .gblob{position:absolute;border-radius:50%;opacity:.55;animation:gfloat var(--gd,28s) ease-in-out infinite alternate;}
  .gblob.b1{width:48vmax;height:48vmax;left:-14vmax;top:-10vmax;background:radial-gradient(circle at 32% 32%,#1d5a6e,transparent 66%);--gd:31s;}
  .gblob.b2{width:42vmax;height:42vmax;right:-12vmax;top:20%;background:radial-gradient(circle at 60% 40%,#4d3a78,transparent 66%);--gd:37s;animation-delay:-11s;}
  .gblob.b3{width:38vmax;height:38vmax;left:6%;bottom:-16vmax;background:radial-gradient(circle at 50% 50%,#6e4a1d,transparent 62%);--gd:26s;animation-delay:-19s;}
  @keyframes gfloat{from{transform:translate(0,0) scale(1);}to{transform:translate(6vmax,-5vmax) scale(1.14);}}
  .app{background:linear-gradient(180deg,rgba(19,25,33,.58) 0%,rgba(13,17,22,.66) 44%,rgba(9,12,16,.78) 100%);}
  .app::before{opacity:.6;}
  .topbar{background:linear-gradient(180deg,rgba(22,28,35,.42),rgba(15,19,24,.28));border-bottom-color:rgba(255,255,255,.10);}
  .station,.qmode,.today,.chartcard,.gitem,.statusrep,.stat,.entry,.qcard,.blindtog,.tdcountcta,.toast,.chcard{
    background:rgba(255,255,255,.055);
    border-color:rgba(255,255,255,.15);
    backdrop-filter:blur(20px) saturate(1.55);
    -webkit-backdrop-filter:blur(20px) saturate(1.55);
    box-shadow:inset 0 1px 0 rgba(255,255,255,.20),inset 0 -1px 0 rgba(0,0,0,.18),0 12px 34px rgba(0,0,0,.38);
  }
  .opt,.fb,.chip,.mc,.rvchip,.kbtn,.recbtn,.sumchips span,.btn.ghost,.gauge,.searchbar{
    background:rgba(255,255,255,.05);
    border-color:rgba(255,255,255,.14);
    backdrop-filter:blur(14px) saturate(1.4);
    -webkit-backdrop-filter:blur(14px) saturate(1.4);
  }
  .opt.correct{background:rgba(98,204,131,.14);}
  .opt.wrong{background:rgba(233,106,81,.13);}
  .opt.sel,.blindrun .opt.bsel{background:rgba(118,196,216,.16)!important;}
  .hero{border-color:rgba(255,255,255,.20);box-shadow:inset 0 1px 0 rgba(255,255,255,.25),0 24px 60px rgba(0,0,0,.55);}
  .sheet{background:rgba(26,33,41,.62);border:1px solid rgba(255,255,255,.16);border-bottom:none;}
  @media (max-width:899px){
    .nav{left:50%;bottom:10px;width:calc(100% - 24px);max-width:438px;border-radius:26px;border:1px solid rgba(255,255,255,.16);border-top:1px solid rgba(255,255,255,.22);background:rgba(20,26,33,.5);box-shadow:0 18px 44px rgba(0,0,0,.55),inset 0 1px 0 rgba(255,255,255,.16);padding:9px 4px 9px;}
    .screen{padding-bottom:112px;}
  }
  @media (min-width:900px){
    .nav{background:rgba(15,20,26,.45);backdrop-filter:blur(26px) saturate(1.6);-webkit-backdrop-filter:blur(26px) saturate(1.6);}
  }
  #screen{perspective:1100px;}
  .view.on{transform-style:preserve-3d;}
  @keyframes viewIn{0%{opacity:.3;transform:translateY(16px) rotateX(4deg) translateZ(-36px);}100%{opacity:1;transform:none;}}
  @keyframes slideInR{0%{opacity:.3;transform:translateX(40px) rotateY(-11deg) translateZ(-52px);}100%{opacity:1;transform:none;}}
  @keyframes slideInL{0%{opacity:.3;transform:translateX(-40px) rotateY(11deg) translateZ(-52px);}100%{opacity:1;transform:none;}}
  .view.on.slide-r,.view.on.slide-l{animation-duration:.46s;}
  @keyframes glasspulse{0%,100%{box-shadow:inset 0 1px 0 rgba(255,255,255,.20),inset 0 -1px 0 rgba(0,0,0,.18),0 12px 34px rgba(0,0,0,.38);}50%{box-shadow:inset 0 1px 0 rgba(255,255,255,.30),inset 0 -1px 0 rgba(0,0,0,.18),0 12px 40px rgba(0,0,0,.45);}}
  .today{animation:glasspulse 7s ease-in-out infinite;}
  .hero{height:232px;}
  .hero::before{content:"";position:absolute;inset:0;border-radius:20px;box-shadow:inset 0 0 0 1px rgba(255,255,255,.08),inset 0 0 44px rgba(118,196,216,.10);z-index:3;pointer-events:none;}
  .nextact{background:linear-gradient(135deg,rgba(244,173,61,.18),rgba(244,173,61,.05)) padding-box,conic-gradient(from var(--ctaa),rgba(244,173,61,.28) 0 68%,rgba(244,173,61,.95) 84%,rgba(244,173,61,.28) 96%) border-box;backdrop-filter:blur(16px) saturate(1.5);-webkit-backdrop-filter:blur(16px) saturate(1.5);box-shadow:inset 0 1px 0 rgba(255,255,255,.16),0 10px 30px rgba(0,0,0,.35);}
  @media (max-width:899px){
    .navbtn::before{display:none;}
    .navbtn{border-radius:18px;margin:0 2px;transition:background var(--d2),color var(--d2);}
    .navbtn.on{background:rgba(118,196,216,.14);box-shadow:inset 0 1px 0 rgba(255,255,255,.14);}
  }
  @media (min-width:900px){
    #v-home .pad>.hero{height:340px;}
    .navmeta{background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.09);border-radius:14px;padding:14px 13px;}
  }
  .splash{background:rgba(9,12,16,.55);backdrop-filter:blur(26px) saturate(1.4);-webkit-backdrop-filter:blur(26px) saturate(1.4);}
  #scrim,.scrim{backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);}
  .sectlabel{color:rgba(255,255,255,.44);}
  .sectlabel::before{box-shadow:0 0 8px var(--glassdim);}
  .btn.primary{box-shadow:0 1px 0 rgba(255,255,255,.5) inset,0 -2px 6px rgba(140,80,0,.3) inset,0 10px 26px rgba(244,173,61,.32),0 2px 5px rgba(0,0,0,.3);}
  .fxripple{mix-blend-mode:overlay;}
  @media (prefers-reduced-motion:reduce){.gblob,.today{animation:none!important;}}
</style>"""

GLASS_JS = """/* LIQUID GLASS build: drifting color-field behind the app */
(function(){
  var g=document.createElement('div');g.className='glassbg';g.setAttribute('aria-hidden','true');
  g.innerHTML='<div class="gblob b1"></div><div class="gblob b2"></div><div class="gblob b3"></div>';
  document.body.insertBefore(g,document.body.firstChild);
})();

/* INIT */"""


def replace(html, old, new, n=1):
    count = html.count(old)
    assert count == n, f"expected {n} occurrence(s) of {old[:70]!r}, found {count}"
    return html.replace(old, new)


def main():
    h = open(SRC, encoding="utf-8").read()
    h = replace(h, "<title>CAPM Prep — Floor by Floor</title>",
                "<title>CAPM Prep — Liquid Glass</title>")
    h = replace(h, "EXAM READINESS \\u00b7 FLOOR BY FLOOR",
                "LIQUID GLASS \\u00b7 FLOOR BY FLOOR")
    h = replace(h, "</style>", GLASS_CSS)
    h = replace(h, "/* INIT */", GLASS_JS)
    open(OUT, "w", encoding="utf-8").write(h)
    print(f"wrote {OUT} ({len(h):,} bytes)")


if __name__ == "__main__":
    main()
